version: "3.6"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    volumes:
      - /srv/docker/plex/config:/config
      - /data/tv:/tv
      - /data/movies:/movies
    ports:
      - 32400:32400
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/shared
    environment:
      - TZ=Europe/Stockholm

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    volumes:
      - /srv/docker/qbittorrent/config:/config
      - /data/downloads:/downloads
    ports:
      - 8086:8086
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - UMASK_SET=002
      - WEBUI_PORT=8086

  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    volumes:
      - /srv/docker/sabnzbd/config:/config
      - /data/downloads:/downloads
      - /data/incomplete-downloads:/incomplete-downloads
    ports:
        - 8888:8080
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - /srv/docker/radarr/config:/config
      - /data/downloads:/downloads
      - /data/movies:/movies
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7878:7878
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /srv/docker/sonarr/config:/config
      - /data/tv:/tv
      - /etc/localtime:/etc/localtime:ro
    ports:
        - 8989:8989
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    volumes:
      - /srv/docker/jackett/config:/config
      - /data/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9117:9117
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
